name: Build & Release Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PlatformIO
      uses: platformio/action-setup@v2

    - name: Build firmware
      run: platformio run

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v3
      with:
        name: firmware
        path: .pio/build/*/firmware.bin

    - name: Update version.json
      run: |
        echo '{"version":"1.0.$GITHUB_RUN_NUMBER"}' > version.json
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add version.json
        git commit -m "Update firmware version"
        git push
